source $HOME/.config/nvim/themes/airline.vim
source $HOME/.config/nvim/plugins/plugins.vim
source $HOME/.config/nvim/plugins/nvimtree.vim
source $HOME/.config/nvim/plugins/coc.vim
source $HOME/.config/nvim/plugins/autosave.vim
source $HOME/.config/nvim/settings/general.vim
"source $HOME/.config/nvim/themes/onedark.vim
"source $HOME/.config/nvim/themes/material.vim
"source $HOME/.config/nvim/plugins/blankline.vim
